# Generated by Django 6.0 on 2026-03-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SU', 'Superuser'), ('MG', 'Manager'), ('AC', 'Accountant'), ('RD', 'Rider'), ('CS', 'Customer Support')], default='RD', max_length=5),
        ),
    ]
