# Generated by Django 6.0 on 2026-03-26 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_approve_orders', models.BooleanField(default=False)),
                ('can_view_orders', models.BooleanField(default=False)),
                ('can_cancel_orders', models.BooleanField(default=False)),
                ('can_add_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_manage_bills', models.BooleanField(default=False)),
                ('can_add_bills', models.BooleanField(default=False)),
                ('can_edit_bills', models.BooleanField(default=False)),
                ('can_manage_invoices', models.BooleanField(default=False)),
                ('can_add_invoices', models.BooleanField(default=False)),
                ('can_edit_invoices', models.BooleanField(default=False)),
                ('is_customer_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('restaurant_number', models.CharField(max_length=20, unique=True)),
                ('tax_number', models.CharField(max_length=20, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedRestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('SU', 'Superuser'), ('MG', 'Manager'), ('AC', 'Accountant'), ('RD', 'Rider'), ('CS', 'Customer Support')], default='RD', max_length=5)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(related_name='user_permissions', to='api.permission')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_users', to='api.restaurant')),
            ],
        ),
    ]
