# Generated by Django 6.0 on 2026-03-26 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_permission_restaurant_connectedrestaurantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedrestaurantuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='connectedrestaurantuser',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectedrestaurantuser',
            name='permissions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='api.permission'),
        ),
    ]
