# Generated by Django 6.0 on 2026-03-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_connectedrestaurantuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.permission'),
        ),
    ]
